version: '3.8'

services:
  backend:
    image: mona233/backend:latest
    container_name: backend
    ports:
      - "8000:8000"
    networks:
      - my_network
    environment:
      - DJANGO_ALLOWED_HOSTS=localhost,127.0.0.1,backend,SERVER_NAME
    volumes:
      - sqlite_db_data:/code/db.sqlite3


  web:
    image: mona233/web:latest
    container_name: web
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - my_network
    environment:
      - API_URL=http://backend:8000/api/posts/

  nginx:
    image: mona233/nginx:latest
    restart: always
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - web
      - backend
    networks:
      - my_network
    environment:
      - SERVER_NAME=localhost
    command: /bin/sh -c "envsubst '\$SERVER_NAME' < /etc/nginx/conf.d/default.conf > /etc/nginx/conf.d/default.conf.tmp && mv /etc/nginx/conf.d/default.conf.tmp /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30 backend web nginx

networks:
  my_network:
    driver: bridge

volumes:
  sqlite_db_data: