version: '3.8'

services:
  backend:
    image: mona233/appleblog_backend:latest
    container_name: backend
    ports:
      - "8000:8000"
    networks:
      - appleblog_network
    environment:
      - DJANGO_ALLOWED_HOSTS=localhost,127.0.0.1,backend,SERVER_NAME
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pYrdip-kevset-mihby2
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    depends_on:
      - db
    volumes:
      - ./media/post_images:/app/media/post_images

  web:
    image: mona233/appleblog_web:latest
    container_name: web
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - appleblog_network
    environment:
      - API_URL=http://backend:8000/api/posts/
      - WEBCONFIG_API_URL=http://backend:8000/api/web_config

  db:
    image: postgres:latest
    container_name: db
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pYrdip-kevset-mihby2

    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      - appleblog_network

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 60 backend web

networks:
  appleblog_network:
    driver: bridge

volumes:
  postgres_data: