version: '3.8'
services:
  nginx:
    image: nginx:latest
    container_name: nginx_optimized
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro  # 绑定配置文件
      - ./html:/usr/share/nginx/html:ro        # 绑定静态文件目录
    network_mode: host  # 使用主机的网络模式