# Generated by Django 5.0.6 on 2024-05-16 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('cover_url', models.URLField(blank=True, null=True)),
                ('tags', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
