# Generated by Django 5.0.6 on 2024-07-09 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_cover_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='cover_image',
            new_name='image',
        ),
    ]
