# Generated by Django 5.0.6 on 2024-07-09 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_rename_cover_image_post_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='image',
            new_name='cover_image',
        ),
    ]
