# Generated by Django 5.0.6 on 2024-07-09 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='cover_image',
        ),
    ]
