# Generated by Django 5.0.6 on 2024-07-12 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_remove_post_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='theme',
            field=models.CharField(choices=[('light', 'AUTO'), ('dark', 'Dark')], default='light', max_length=10),
        ),
    ]
